from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 800)
        self.pushButton_1 = QtWidgets.QPushButton(Form)
        self.pushButton_1.setGeometry(QtCore.QRect(50, 20, 97, 27))
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(50, 50, 97, 27))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(50, 80, 97, 27))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(170, 20, 97, 27))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(170, 50, 97, 27))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(410, 80, 97, 27))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(Form)
        self.pushButton_7.setGeometry(QtCore.QRect(290, 20, 97, 27))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(Form)
        self.pushButton_8.setGeometry(QtCore.QRect(410, 20, 97, 27))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(Form)
        self.pushButton_9.setGeometry(QtCore.QRect(530, 20, 97, 27))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(Form)
        self.pushButton_10.setGeometry(QtCore.QRect(650, 20, 97, 27))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(Form)
        self.pushButton_11.setGeometry(QtCore.QRect(650, 50, 97, 27))
        self.pushButton_11.setObjectName("pushButton_11")

        self.slidern_1 = QtWidgets.QSlider(Qt.Horizontal, Form)
        self.slidern_1.setGeometry(QtCore.QRect(290, 55, 97, 22))
        self.slidern_1.setObjectName("slider_1")
        self.slidern_1.setValue(49)
        self.slidern_2 = QtWidgets.QSlider(Qt.Horizontal, Form)
        self.slidern_2.setGeometry(QtCore.QRect(410, 55, 97, 22))
        self.slidern_2.setObjectName("slider_2")
        self.slidern_2.setValue(49)
        self.slidern_3 = QtWidgets.QSlider(Qt.Horizontal, Form)
        self.slidern_3.setGeometry(QtCore.QRect(530, 55, 97, 22))
        self.slidern_3.setObjectName("slider_3")
        self.slidern_3.setValue(49)

        self.graphicsView_1 = QtWidgets.QGraphicsView(Form)
        self.graphicsView_1.setGeometry(QtCore.QRect(100, 160, 256, 256))
        self.graphicsView_1.setObjectName("graphicsView_1")
        self.graphicsView_2 = QtWidgets.QGraphicsView(Form)
        self.graphicsView_2.setGeometry(QtCore.QRect(440, 160, 256, 256))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.graphicsView_3 = QtWidgets.QGraphicsView(Form)
        self.graphicsView_3.setGeometry(QtCore.QRect(100, 500,  256, 256))
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.graphicsView_4 = QtWidgets.QGraphicsView(Form)
        self.graphicsView_4.setGeometry(QtCore.QRect(440, 500,  256, 256))
        self.graphicsView_4.setObjectName("graphicsView_4")

        self.retranslateUi(Form)
        self.pushButton_1.clicked.connect(Form.open)
        self.pushButton_2.clicked.connect(Form.open_ref)
        self.pushButton_3.clicked.connect(Form.save_img)
        self.pushButton_4.clicked.connect(Form.clear)
        self.pushButton_5.clicked.connect(Form.apply)
        self.pushButton_6.clicked.connect(Form.skin_mode)
        self.pushButton_7.clicked.connect(Form.nose_mode)
        self.pushButton_8.clicked.connect(Form.eyes_mode)
        self.pushButton_9.clicked.connect(Form.mouth_mode)
        self.pushButton_10.clicked.connect(Form.man_mode)
        self.pushButton_11.clicked.connect(Form.woman_mode)

        self.slidern_1.valueChanged.connect(Form.slider)
        self.slidern_2.valueChanged.connect(Form.slider)
        self.slidern_3.valueChanged.connect(Form.slider)


        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "FacialGAN"))
        self.pushButton_1.setText(_translate("Form", "Open Image"))
        self.pushButton_2.setText(_translate("Form", "Open Ref"))
        self.pushButton_3.setText(_translate("Form", "Save Image"))
        self.pushButton_4.setText(_translate("Form", "Clear"))
        self.pushButton_5.setText(_translate("Form", "Apply"))
        self.pushButton_6.setText(_translate("Form", "Eraser"))
        self.pushButton_7.setText(_translate("Form", "Nose"))
        self.pushButton_8.setText(_translate("Form", "Eyes"))
        self.pushButton_9.setText(_translate("Form", "Mouth"))
        self.pushButton_10.setText(_translate("Form", "Man"))
        self.pushButton_11.setText(_translate("Form", "Woman"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
